---
- name: Install Rancher
  hosts: control
  vars:
    docker_version: 18.09
    docker_install_script: https://releases.rancher.com/install-docker/{{ docker_version }}.sh
    rancher_version: 2.3.4

  tasks:

    - name: Install Docker
      shell: curl {{ docker_install_script }} | sh
      args:
        creates: /usr/bin/docker-init

    - name: Run Rancher
      docker_container:
        name: rancher
        image: rancher/rancher:v{{ rancher_version }}
        restart_policy: unless-stopped
        ports:
          - "80:80"
          - "443:443"

- name: K3sup
  hosts: control

  tasks:
    - name: Install
      raw: curl -sLS https://get.k3sup.dev | sh


TODO: WIP
