---

- name: Rancher
  hosts: rancher
  vars:
    docker_version: 18.09
    docker_install_script: https://releases.rancher.com/install-docker/{{ docker_version }}.sh
    rancher_version: 2.3.5

  tasks:

    - name: Install Docker
      shell: curl {{ docker_install_script }} | sh
      args:
        creates: /usr/bin/docker
      tags:
        - docker

    - name: Run Rancher
      docker_container:
        name: rancher
        image: rancher/rancher:v{{ rancher_version }}-linux-arm64
        restart_policy: unless-stopped
        ports:
          - "80:80"
          - "443:443"
      tags:
        - docker

- name: K3sup
  hosts: control
  become: no

  tasks:
    - name: Download k3sup
      become: yes
      shell: curl -SLfs https://get.k3sup.dev | sh
      tags:
        - k3sup

    - name: Master Leader
      shell: k3sup install --ip 192.168.178.205 --user node --cluster
      tags:
        - k3sup

    - name: Workers
      shell: k3sup join --ip {{ item }} --server-ip 192.168.178.205 --user node
      with_items:
        - 192.168.178.201
        - 192.168.178.202
        - 192.168.178.203
      tags:
        - k3sup

    - name: Master Followers
      shell: k3sup join --ip {{ item }} --user node --server-user node --server-ip 192.168.178.205 --server
      with_items:
        - 192.168.178.206
        - 192.168.178.207
      tags:
        - k3sup
