---

- name: K3sup
  hosts: control
  become: no

  tasks:
    - name: Download k3sup
      shell: curl -sLS https://get.k3sup.dev | sh

    - name: Master
      shell: k3sup install --ip 192.168.178.205 --user node

    - name: Workers
      shell: k3sup join --ip {{ item }} --server-ip 192.168.178.205 --user $USER
      with_items:
        - 192.168.178.201
        - 192.168.178.202
        - 192.168.178.203


