// GENERATED FILE - DO NOT CHANGE!
// Generated by running 'config.sh' script

variable "rancher_api_url" {
  type = "string"
  description = "Endpoint for the Rancher API"
  default = "https://192.168.178.201/v3"
}

variable "rancher_cluster_name" {
  type = "string"
  description = "Name of the rancher cluster that's being created"
  default = "home"
}

variable "rancher_token_lookup" {
  default = "http://192.168.178.201:8500/v1/kv/rancher/token?raw"
}

variable "rancher_server_url" {
  default = "https://192.168.178.201"
}

variable "rancher_network_plugin" {
  default = "flannel"
}
#
# variable "mysql_root_password" {
#   default = "root123"
# }
#
# variable "mysql_username" {
#   default = "admin"
# }
#
# variable "mysql_password" {
#   default = "admin"
# }
#
# variable "project_domain_name" {
#   default = ""
# }
#
# variable "user_domain_name" {
#   default = "None"
# }
#
# variable "network_name" {
#   default = "dev-{ECG_USERNAME}-net"
# }
#
# variable "ssh_key_public" {
#   default = "/home/vagrant/.ssh/id_rsa.pub"
# }
#
# variable "ssh_key_private" {
#   default = "/home/vagrant/.ssh/id_rsa"
# }
#
