- name: Setup nodes
  hosts: all

  vars:

  tasks:
    - name: remove /etc/machine-id
      file:
        path: /etc/machine-id
        state: absent
    - name: remove /var/lib/dbus/machine-id
      file:
        path: /var/lib/dbus/machine-id
        state: absent
    - name: generate new machine-id
      command: systemd-machine-id-setup
      notify: reboot

    - name: change hostname
      hostname:
        name: "{{ inventory_hostname }}"
      notify: reboot

    - name: update packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # 1 day

#    - name: install lxd
#      todo

  handlers:
    - name: reboot node
      shell: sleep 2 && shutdown -r now "rebooting, please wait"
      async: 1
      poll: 0
      ignore_errors: true
      listen: "reboot"

    - name: wait for node to come back
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      listen: "reboot"
