---

- hosts: all
  vars_files: variables.yml
  gather_facts: no

  pre_tasks:

    - name: Wait for servers
      wait_for_connection:

  tasks:

    - name: Remove Containers
      shell: docker rm -f $(docker ps -qa)
      ignore_errors: yes

    - name: Remove Images
      shell: docker rmi -f $(docker images -q)
      ignore_errors: yes

    - name: Remove Volumes
      shell: docker volume rm $(docker volume ls -q)
      ignore_errors: yes

    - name: Unmount
      shell: for mount in $(mount | grep tmpfs | grep '/var/lib/kubelet' | awk '{ print $3 }') /var/lib/kubelet /var/lib/rancher; do umount $mount; done
      ignore_errors: yes

    - name: Remove directories
      shell: rm -rf /etc/ceph /etc/cni /etc/kubernetes /opt/cni /opt/rke /run/secrets/kubernetes.io /run/calico /run/flannel /var/lib/calico /var/lib/etcd /var/lib/cni /var/lib/kubelet /var/lib/rancher/rke/log /var/log/containers /var/log/pods /var/run/calico
      ignore_errors: yes

#    - name: Reboot
#      shell: reboot
#      ignore_errors: yes
