---

- name: Reboot all nodes
  hosts: all
  tasks:
    - name: reboot node
      shell: sleep 2 && shutdown -r now "rebooting, please wait"
      async: 1
      poll: 0
      ignore_errors: true

    - name: wait for node to come back
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300


