---
- name: Install Rancher Master
  hosts: m1

  tasks:
    - name: Start Rancher
      docker_container:
        name: rancher
        image: rancher/rancher:stable
        restart_policy: unless-stopped
        published_ports:
          - "80:80"
          - "443:443"
        state: started

